### ISSUE TITLE
Compatibility with FFMpeg-5.0

### ISSUE THREAD

**Issue by sagitter** [salsaman/LiVES#49]
Hi.

LiVES is not compiling against new `FFMpeg-5.0` Are you interested to support it?

```
/bin/sh ../../../../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"LiVES\" -DPACKAGE_TARNAME=\"lives\" -DPACKAGE_VERSION=\"3.2.0\" -DPACKAGE_STRING=\"LiVES\ 3.2.0\" -DPACKAGE_BUGREPORT=\"https://github.com/salsaman/LiVES/issues\" -DPACKAGE_URL=\"http://lives-video.com\" -DPACKAGE=\"lives\" -DVERSION=\"3.2.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSTDC_HEADERS=1 -DGETTEXT_PACKAGE=\"lives\" -DLOCALEDIR=\"/usr/share/locale\" -DPREFIX=\"/usr\" -DLiVES_VERSION=\"3.2.0\" -DHAVE_VISIBILITY=1 -DHAVE_STDINT_H_WITH_UINTMAX=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DINTDIV0_RAISES_SIGFPE=1 -DHAVE_INTTYPES_H_WITH_UINTMAX=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DHAVE_UINTMAX_T=1 -DHAVE_INTTYPES_H=1 -DUSE_POSIX_THREADS=1 -DUSE_POSIX_THREADS_WEAK=1 -DHAVE_PTHREAD_RWLOCK=1 -DHAVE_PTHREAD_MUTEX_RECURSIVE=1 -DHAVE_BUILTIN_EXPECT=1 -DHAVE_ARGZ_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIMITS_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETCWD=1 -DHAVE_GETEGID=1 -DHAVE_GETEUID=1 -DHAVE_GETGID=1 -DHAVE_GETUID=1 -DHAVE_MEMPCPY=1 -DHAVE_MUNMAP=1 -DHAVE_STPCPY=1 -DHAVE_STRCASECMP=1 -DHAVE_STRDUP=1 -DHAVE_STRTOUL=1 -DHAVE_TSEARCH=1 -DHAVE_ARGZ_COUNT=1 -DHAVE_ARGZ_STRINGIFY=1 -DHAVE_ARGZ_NEXT=1 -DHAVE___FSETLOCKING=1 -DHAVE_DECL_FEOF_UNLOCKED=1 -DHAVE_DECL_FGETS_UNLOCKED=1 -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_NL_LOCALE_NAME=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_WCHAR_T=1 -DHAVE_WINT_T=1 -DHAVE_INTMAX_T=1 -DHAVE_POSIX_PRINTF=1 -DHAVE_STDINT_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_ASPRINTF=1 -DHAVE_FWPRINTF=1 -DHAVE_PUTENV=1 -DHAVE_SETENV=1 -DHAVE_SETLOCALE=1 -DHAVE_SNPRINTF=1 -DHAVE_WCSLEN=1 -DHAVE_DECL__SNPRINTF=0 -DHAVE_DECL__SNWPRINTF=0 -DHAVE_DECL_GETC_UNLOCKED=1 -DHAVE_LANGINFO_CODESET=1 -DHAVE_LC_MESSAGES=1 -DENABLE_NLS=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -DHAVE_LIBDL=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_POSIX_FALLOCATE=1 -DHAVE_GETENTROPY=1 -DHAVE_SYS_PRCTL_H=1 -DHAVE_LINUX_JOYSTICK_H=1 -DHAVE_JACK_TRANSPORT_H=1 -DHAVE_BZLIB_H=1 -DHAVE_LADSPA_H=1 -DHAVE_LINUX_VIDEODEV2_H=1 -DHAVE_FREI0R_H=1 -DHAVE_LIBRAW1394_RAW1394_H=1 -DHAVE_LIBAVC1394_AVC1394_H=1 -DHAVE_LIBAVC1394_ROM1394_H=1 -I.   -I/usr/include/tirpc  -I/usr/include/opencv4  -DHAVE_LIBAV_LIBS=1 -Wno-unused-function -DHAVE_AVCODEC_OPEN2=1 -DHAVE_AVCODEC_ALLOC_CONTEXT3=1 -DHAVE_AVCODEC_GET_NAME=1  -DHAVE_AVFORMAT_NEW_STREAM=1 -DHAVE_AVPACKET_UNREF=1 -DHAVE_AVFRAME_UNREF=1 -DHAVE_AVFORMAT_FIND_STREAM_INFO=1 -DHAVE_AVFORMAT_CLOSE_INPUT=1   -DHAVE_AVPRIV_SET_PTS_INFO=1 -fPIC -DPIC -Wno-unused-variable  -DNEED_LOCAL_WEED -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -Wno-deprecated-declarations -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o libav_stream_la-libav_stream.lo `test -f 'libav_stream.c' || echo './'`libav_stream.c
libtool: compile:  gcc -DPACKAGE_NAME=\"LiVES\" -DPACKAGE_TARNAME=\"lives\" -DPACKAGE_VERSION=\"3.2.0\" "-DPACKAGE_STRING=\"LiVES 3.2.0\"" -DPACKAGE_BUGREPORT=\"https://github.com/salsaman/LiVES/issues\" -DPACKAGE_URL=\"http://lives-video.com\" -DPACKAGE=\"lives\" -DVERSION=\"3.2.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSTDC_HEADERS=1 -DGETTEXT_PACKAGE=\"lives\" -DLOCALEDIR=\"/usr/share/locale\" -DPREFIX=\"/usr\" -DLiVES_VERSION=\"3.2.0\" -DHAVE_VISIBILITY=1 -DHAVE_STDINT_H_WITH_UINTMAX=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DINTDIV0_RAISES_SIGFPE=1 -DHAVE_INTTYPES_H_WITH_UINTMAX=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DHAVE_UINTMAX_T=1 -DHAVE_INTTYPES_H=1 -DUSE_POSIX_THREADS=1 -DUSE_POSIX_THREADS_WEAK=1 -DHAVE_PTHREAD_RWLOCK=1 -DHAVE_PTHREAD_MUTEX_RECURSIVE=1 -DHAVE_BUILTIN_EXPECT=1 -DHAVE_ARGZ_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIMITS_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETCWD=1 -DHAVE_GETEGID=1 -DHAVE_GETEUID=1 -DHAVE_GETGID=1 -DHAVE_GETUID=1 -DHAVE_MEMPCPY=1 -DHAVE_MUNMAP=1 -DHAVE_STPCPY=1 -DHAVE_STRCASECMP=1 -DHAVE_STRDUP=1 -DHAVE_STRTOUL=1 -DHAVE_TSEARCH=1 -DHAVE_ARGZ_COUNT=1 -DHAVE_ARGZ_STRINGIFY=1 -DHAVE_ARGZ_NEXT=1 -DHAVE___FSETLOCKING=1 -DHAVE_DECL_FEOF_UNLOCKED=1 -DHAVE_DECL_FGETS_UNLOCKED=1 -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_NL_LOCALE_NAME=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_WCHAR_T=1 -DHAVE_WINT_T=1 -DHAVE_INTMAX_T=1 -DHAVE_POSIX_PRINTF=1 -DHAVE_STDINT_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_ASPRINTF=1 -DHAVE_FWPRINTF=1 -DHAVE_PUTENV=1 -DHAVE_SETENV=1 -DHAVE_SETLOCALE=1 -DHAVE_SNPRINTF=1 -DHAVE_WCSLEN=1 -DHAVE_DECL__SNPRINTF=0 -DHAVE_DECL__SNWPRINTF=0 -DHAVE_DECL_GETC_UNLOCKED=1 -DHAVE_LANGINFO_CODESET=1 -DHAVE_LC_MESSAGES=1 -DENABLE_NLS=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -DHAVE_LIBDL=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_POSIX_FALLOCATE=1 -DHAVE_GETENTROPY=1 -DHAVE_SYS_PRCTL_H=1 -DHAVE_LINUX_JOYSTICK_H=1 -DHAVE_JACK_TRANSPORT_H=1 -DHAVE_BZLIB_H=1 -DHAVE_LADSPA_H=1 -DHAVE_LINUX_VIDEODEV2_H=1 -DHAVE_FREI0R_H=1 -DHAVE_LIBRAW1394_RAW1394_H=1 -DHAVE_LIBAVC1394_AVC1394_H=1 -DHAVE_LIBAVC1394_ROM1394_H=1 -I. -I/usr/include/tirpc -I/usr/include/opencv4 -DHAVE_LIBAV_LIBS=1 -Wno-unused-function -DHAVE_AVCODEC_OPEN2=1 -DHAVE_AVCODEC_ALLOC_CONTEXT3=1 -DHAVE_AVCODEC_GET_NAME=1 -DHAVE_AVFORMAT_NEW_STREAM=1 -DHAVE_AVPACKET_UNREF=1 -DHAVE_AVFRAME_UNREF=1 -DHAVE_AVFORMAT_FIND_STREAM_INFO=1 -DHAVE_AVFORMAT_CLOSE_INPUT=1 -DHAVE_AVPRIV_SET_PTS_INFO=1 -fPIC -DPIC -Wno-unused-variable -DNEED_LOCAL_WEED -I/usr/include/ffmpeg -I/usr/include/ffmpeg -I/usr/include/ffmpeg -I/usr/include/ffmpeg -I/usr/include/ffmpeg -Wno-deprecated-declarations -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c libav_stream.c  -fPIC -DPIC -o .libs/libav_stream_la-libav_stream.o
make[4]: Leaving directory '/builddir/build/BUILD/lives-3.2.0/lives-plugins/plugins/playback/video'
libav_stream.c: In function 'module_check_init':
libav_stream.c:114:3: warning: implicit declaration of function 'av_register_all' [-Wimplicit-function-declaration]
  114 |   av_register_all();
      |   ^~~~~~~~~~~~~~~
libav_stream.c: In function 'add_stream':
libav_stream.c:441:10: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  441 |   *codec = avcodec_find_encoder(codec_id);
      |          ^
libav_stream.c:465:10: error: 'AVStream' has no member named 'codec'
  465 |   ost->st->codec = ost->enc = c;
      |          ^~
libav_stream.c: In function 'init_screen':
libav_stream.c:588:30: error: 'AVStream' has no member named 'codec'
  588 |   ostv.enc = encctx = vStream->codec;
      |                              ^~
libav_stream.c:610:10: error: 'AVStream' has no member named 'codec'
  610 |   vStream->codec->time_base = vStream->time_base;
      |          ^~
libav_stream.c:612:10: error: 'AVStream' has no member named 'codec'
  612 |   vStream->codec->width = width;
      |          ^~
libav_stream.c:613:10: error: 'AVStream' has no member named 'codec'
  613 |   vStream->codec->height = height;
      |          ^~
libav_stream.c:614:10: error: 'AVStream' has no member named 'codec'
  614 |   vStream->codec->pix_fmt = avpalette;
      |          ^~
libav_stream.c:619:10: error: 'AVStream' has no member named 'codec'
  619 |   vStream->codec->bit_rate = maxvbitrate;
      |          ^~
libav_stream.c:631:14: error: 'AVStream' has no member named 'codec'
  631 |       vStream->codec->qmin = 10;
      |              ^~
libav_stream.c:632:14: error: 'AVStream' has no member named 'codec'
  632 |       vStream->codec->qmax = 51;
      |              ^~
libav_stream.c:652:12: error: 'AVStream' has no member named 'codec'
  652 |     vStream->codec->max_b_frames = 2;
      |            ^~
libav_stream.c:658:12: error: 'AVStream' has no member named 'codec'
  658 |     vStream->codec->mb_decision = 2;
      |            ^~
libav_stream.c:681:33: error: 'AVStream' has no member named 'codec'
  681 |     osta.enc = aencctx = aStream->codec;
      |                                 ^~
libav_stream.c: In function 'render_audio_frame_float':
libav_stream.c:875:11: warning: implicit declaration of function 'avcodec_encode_audio2'; did you mean 'avcodec_encode_subtitle'? [-Wimplicit-function-declaration]
  875 |     ret = avcodec_encode_audio2(c, &pkt, NULL, &got_packet);
      |           ^~~~~~~~~~~~~~~~~~~~~
      |           avcodec_encode_subtitle
libav_stream.c: In function 'render_frame_yuv420':
libav_stream.c:988:11: warning: implicit declaration of function 'avcodec_encode_video2'; did you mean 'avcodec_encode_subtitle'? [-Wimplicit-function-declaration]
  988 |     ret = avcodec_encode_video2(c, &pkt, ostv.frame, &got_packet);
      |           ^~~~~~~~~~~~~~~~~~~~~
      |           avcodec_encode_subtitle
libav_stream.c: In function 'exit_screen':
libav_stream.c:1090:26: error: 'AVStream' has no member named 'codec'
 1090 |     avcodec_close(vStream->codec);
      |                          ^~
libav_stream.c:1095:26: error: 'AVStream' has no member named 'codec'
 1095 |     avcodec_close(aStream->codec);
      |                          ^~
make[4]: *** [Makefile:832: libav_stream_la-libav_stream.lo] Error 1
```

**Comment by salsaman** [comment]
Thanks ! Any chance you could provide a patch ? lives-plugins/plugins/decoders/libav-helper.h is specifically designed to handle such things.

**Comment by sagitter** [comment]
> Thanks ! Any chance you could provide a patch ?

No, unfortunately. That's why i ask your help. :)

**Comment by rezso** [comment]
In addition, build fails with ffmpeg 4.4.1 also.
See the attached log snippets.
[ffmpeg4.4.log](https://github.com/salsaman/LiVES/files/8319576/ffmpeg4.4.log)

**Comment by salsaman** [comment]
> In addition, build fails with ffmpeg 4.4.1 also. See the attached log snippets. [ffmpeg4.4.log](https://github.com/salsaman/LiVES/files/8319576/ffmpeg4.4.log)

Please attach the output from 'configure'. The macro substitutions should only happen if the target function is not present.

For example, in configure.ac, there is:

`PKG_CHECK_MODULES(LIBAVCODEC,libavcodec >= 53.0.0,HAVE_AVCODEC=true,HAVE_AVCODEC=false)
`
then:
```
if test "$HAVE_AVCODEC" = "true" ; then
AC_CHECK_LIB(avcodec,avcodec_open2,HAVE_AVCODEC_OPEN2=true,HAVE_AVCODEC_OPEN2=false)
```

etc. then in libav_helper,h:

```
#if !HAVE_AVCODEC_OPEN2
#define avcodec_open2(a, b, c) avcodec_open(a, b)
#endif

```

**Comment by sergiomb2** [comment]
Neither compiles with ffmpeg 4.4.2

mkv_decoder.c:1487:26: warning: implicit declaration of function 'av_new_stream' [-Wimplicit-function-declaration] 

seems av_new_stream is deprecated since 2013 
http://sgros.blogspot.com/2013/01/deprecated-functions-in-ffmpeg-library.html

**Comment by salsaman** [comment]
The question is, why is 'configure' not detecting this and setting the appropriate macros ?

**Comment by sergiomb2** [comment]
> The question is, why is 'configure' not detecting this and setting the appropriate macros ?

you you mean as appropriated macros

https://github.com/salsaman/LiVES/blob/master/lives-plugins/plugins/playback/video/libav_stream.c#L133 don't have any macro

**Comment by sergiomb2** [comment]
OK I found here the "appropriated macros"  https://github.com/salsaman/LiVES/issues/49#issuecomment-1080409594

**Comment by rezso** [comment]
I think, it is a problems with the configure checks.  For example, the configure says 'HAVE_AVCODEC_OPEN2=false', but this function is exists in libavcodec.so.58.91.100.
I removed all libav_helper.h includes, and `pkt->destruct = av_destruct_packet;` from mpegts_decoder.c (AVPacket has no member "destruct").
After this, I can build asf, dv, flv, mkv, mpegts and zzavformat plugins with ffmpeg 4.3.

**Comment by salsaman** [comment]
Apologies for the delay in getting back to looking at this. I have been busy rewriting a lot of the code, which is now in the new LiVES-4.0 branch.

**Comment by salsaman** [comment]
I am still waiting for somebody to attach the complete output from ./configure.
My first guess was that libavcodec was not being detected, so the lib checks were not being done, but that were the case then libavstream plugin ought not to be built.
If it IS being detected then that implies that for example:
AC_CHECK_LIB(avcodec,avcodec_open2,HAVE_AVCODEC_OPEN2=true,HAVE_AVCODEC_OPEN2=false)
is failing, which seems strange, since all that macro should do is check if the function is available in the lib.

Do you have multiple versions of the lib installed ? Somwehre above somebody mentioned compile with libavcodec 4.x. That will not work as the minimumis 53.0.0, which is what configure will check for. configure only checks whether a suitable version is available. Then the script will check the standard lib paths and find the first version whcih matches, which may not necessarily be the same.

**Comment by salsaman** [comment]
If multiple versions are the cause then this can easily be resolved. You just need to specify which version to use, so for example:

./configure LIBAVCODEC_LIBS="-L /usr/lib/x86_64-linux-gnu" LIBAVFORMAT_LIBS=..... LIBAVUTIL_LIBS=.....   LIBSWSCALE_LIBS=..... LIBSWRESAMPLE_LIBS=....

or possibly even ./configure LDFLAGS=-L/p/a/t/h

If there are multiple versions in the same directory then the file can be specified with -l/path_to_lib.so.x.y.z

**Comment by dfandrich** [comment]
ffmpeg 5.1 is out now and the same issue as the OP holds for it as well.

**Comment by VVD** [comment]
ffmpeg 6.0
Build log with errors: https://pkg-status.freebsd.org/package22/data/131amd64-default-foo/2023-04-18_12h28m37s/logs/errors/lives-3.2.0_15.log
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261302#c82

**Comment by salsaman** [comment]
Somebody needs to send a patch for this as I  am focused on the new version.

**Comment by VVD** [comment]
Maybe this can help:
https://stackoverflow.com/questions/71565636/replacing-deprecated-avstream-codec-parameter-in-libav
https://lists.ffmpeg.org/pipermail/libav-user/2016-October/009801.html
https://github.com/opencv/opencv/pull/21754/files

Also FFMPEG 7.0 is released - more deprecations was removed.

**Comment by salsaman** [comment]
thanks will check it out !

**Comment by VVD** [comment]
LiVES planed to remove from FreeBSD ports: https://cgit.freebsd.org/ports/commit/?id=4bd8bfce2c7dce5b0258adca0c84d8b2d93befce
:-(
